let me=null, listings=[], ownerConfigured=false;
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}
function go(id,btn){document.querySelectorAll('.pane').forEach(x=>x.classList.add('hidden'));$(id)?.classList.remove('hidden');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));(btn||document.querySelector(`[data-tab="${id}"]`))?.classList.add('active');if(id==='market')loadMarket();if(id==='matches')loadMatches();if(id==='accountPane')renderAuth();if(id==='adminPane')loadAdmin();window.scrollTo({top:0,behavior:'smooth'})}
async function init(){const [meRes,ownerRes]=await Promise.all([api('/api/me'),api('/api/owner/status')]);me=meRes.user;ownerConfigured=ownerRes.ownerConfigured;renderAccount();renderOwnerSetup();renderFields();await loadMarket()}
function renderAccount(){const admin=$('adminNav');if(admin)admin.classList.toggle('hidden',!(me&&me.role==='owner'));$('account').innerHTML=me?`<span class="tag">${esc(me.name)}${me.role==='owner'?' · OWNER':''}</span> <button class="light" onclick="logout()">Logout</button>`:`<button class="light" onclick="go('accountPane')">Join / Login</button>`}

function renderOwnerSetup(){const box=$('ownerSetup');if(!box)return;if(ownerConfigured){box.innerHTML='';return}box.innerHTML=`<div class="panel ownerSetup"><span class="eyebrow">FIRST-TIME OWNER SETUP</span><h2>Claim this TUT installation</h2><p>Create the one platform-owner account. After this succeeds, owner setup is permanently closed.</p><label>Owner name</label><input id="oName" autocomplete="name"><label>Owner email</label><input id="oEmail" type="email" autocomplete="email"><label>Owner password</label><input id="oPass" type="password" autocomplete="new-password" placeholder="10+ characters"><button class="goldBtn full" onclick="setupOwner()">Create Owner Account</button><div id="oMsg" class="msg"></div><p class="securityNote">Keep this password private. Do not send it in chat or screenshots.</p></div>`}
async function setupOwner(){try{const j=await api('/api/owner/setup',{method:'POST',body:JSON.stringify({name:$('oName').value,email:$('oEmail').value,password:$('oPass').value})});me=j.user;ownerConfigured=true;renderOwnerSetup();renderAccount();go('adminPane')}catch(e){$('oMsg').className='msg error';$('oMsg').textContent=e.message}}
async function loadAdmin(){const area=$('adminArea');if(!area)return;if(!me||me.role!=='owner'){area.innerHTML='<div class="panel"><h2>Owner access required</h2><p>Sign in with the owner account.</p></div>';return}try{const j=await api('/api/admin/summary');area.innerHTML=`<div class="kpis"><div class="kpi"><span>Users</span><b>${j.stats.users}</b></div><div class="kpi"><span>Open listings</span><b>${j.stats.openListings}</b></div><div class="kpi"><span>Matches</span><b>${j.stats.matches}</b></div><div class="kpi"><span>Role</span><b>OWNER</b></div></div><div class="adminGrid"><div class="panel"><h2>Users</h2>${j.users.map(u=>`<div class="adminRow"><div><b>${esc(u.name)}</b><small>${esc(u.email)} · ${esc(u.role)} · ${u.verified?'verified':'pending'}</small></div>${!u.verified?`<button class="light" onclick="verifyUser('${u.id}')">Verify</button>`:''}</div>`).join('')||'<p>No users yet.</p>'}</div><div class="panel"><h2>Listings</h2>${j.listings.slice().reverse().map(x=>`<div class="adminRow"><div><b>${esc(labelType(x.type))}</b><small>${esc(summary(x))} · ${esc(x.status)}</small></div>${x.status==='open'?`<button class="light" onclick="adminClose('${x.id}')">Close</button>`:''}</div>`).join('')||'<p>No listings yet.</p>'}</div></div>`}catch(e){area.innerHTML=`<div class="panel"><p class="error">${esc(e.message)}</p></div>`}}
async function verifyUser(id){await api('/api/admin/users/'+id+'/verify',{method:'POST'});loadAdmin()}
async function adminClose(id){await api('/api/admin/listings/'+id+'/close',{method:'POST'});loadAdmin();loadMarket()}
function renderAuth(){if(me){$('authArea').innerHTML=`<div class="panel"><h2>${esc(me.name)}</h2><p>${esc(me.email)}</p><p><span class="tag">${esc(me.role)}</span><span class="tag">${me.verified?'Verified':'Verification pending'}</span></p><button class="light" onclick="logout()">Logout</button></div>`;return}$('authArea').innerHTML=`<div class="authgrid"><div class="panel"><h2>Create account</h2><label>Name</label><input id="rName"><label>Email</label><input id="rEmail" type="email"><label>Password</label><input id="rPass" type="password" placeholder="8+ characters"><label>Role</label><select id="rRole"><option>driver</option><option>carrier</option><option>shipper</option><option>truck_owner</option><option>warehouse</option></select><button onclick="register()">Register</button><div id="rMsg" class="msg"></div></div><div class="panel"><h2>Login</h2><label>Email</label><input id="lEmail" type="email"><label>Password</label><input id="lPass" type="password"><button onclick="login()">Login</button><div id="lMsg" class="msg"></div></div></div>`}
async function register(){try{const j=await api('/api/register',{method:'POST',body:JSON.stringify({name:$('rName').value,email:$('rEmail').value,password:$('rPass').value,role:$('rRole').value})});me=j.user;renderAccount();go('market')}catch(e){$('rMsg').className='msg error';$('rMsg').textContent=e.message}}
async function login(){try{const j=await api('/api/login',{method:'POST',body:JSON.stringify({email:$('lEmail').value,password:$('lPass').value})});me=j.user;renderAccount();go(me.role==='owner'?'adminPane':'market')}catch(e){$('lMsg').className='msg error';$('lMsg').textContent=e.message}}
async function logout(){await api('/api/logout',{method:'POST'});me=null;renderAccount();go('accountPane')}
const schemas={driver:[['location','Location','text','Dallas, TX'],['date','Available date','date',''],['hours','Hours','number','10'],['license','License','select',['CDL-A','CDL-B']],['experience','Experience years','number','4'],['radius','Radius miles','number','40'],['endorsements','Endorsements','text','Hazmat, Tanker'],['minPay','Minimum pay','number','300']],truck:[['location','Location','text','Dallas, TX'],['date','Available date','date',''],['hours','Hours','number','10'],['equipment','Equipment','select',["Dry Van 53'",'Reefer','Flatbed','Box Truck','Power Only']],['capacity','Capacity lbs','number','45000'],['price','Owner price/day','number','450'],['carrier','Carrier / authority note','text','']],load:[['pickup','Pickup','text','Dallas, TX'],['delivery','Delivery','text','Austin, TX'],['date','Pickup date','date',''],['weight','Weight lbs','number','32000'],['equipment','Equipment required','select',["Dry Van 53'",'Reefer','Flatbed','Box Truck','Power Only']],['budget','Offer / budget','number','1450'],['pallets','Pallets','number','18']],warehouse:[['location','Location','text','Dallas, TX'],['from','From','date',''],['to','To','date',''],['pallets','Pallet positions','number','200'],['price','Price / pallet / day','number','1.8'],['capabilities','Capabilities','text','Dock, forklift']],storage_need:[['location','Location','text','Dallas, TX'],['from','From','date',''],['to','To','date',''],['pallets','Pallets needed','number','80'],['budget','Max / pallet / day','number','2.4'],['requirements','Requirements','text','Forklift']]};
function renderFields(){const type=$('type').value;$('fields').innerHTML=schemas[type].map(([k,l,t,p])=>`<label>${l}</label>${t==='select'?`<select data-k="${k}">${p.map(x=>`<option>${esc(x)}</option>`).join('')}</select>`:`<input data-k="${k}" type="${t}" placeholder="${esc(p)}">`}`).join('')}
async function submitListing(){if(!me){$('postMsg').className='msg error';$('postMsg').textContent='Login first.';return}const data={};$('fields').querySelectorAll('[data-k]').forEach(el=>data[el.dataset.k]=el.type==='number'?Number(el.value||0):el.value);try{await api('/api/listings',{method:'POST',body:JSON.stringify({type:$('type').value,data})});$('postMsg').className='msg';$('postMsg').textContent='Listing published.';await loadMarket()}catch(e){$('postMsg').className='msg error';$('postMsg').textContent=e.message}}
function labelType(t){return {driver:'Driver available',truck:'Truck available',load:'Load',warehouse:'Warehouse capacity',storage_need:'Storage needed'}[t]||t}
function summary(x){const d=x.data;if(x.type==='driver')return `${d.location||'—'} · ${d.license||'—'} · ${d.date||'—'} · min $${d.minPay||0}`;if(x.type==='truck')return `${d.location||'—'} · ${d.equipment||'—'} · ${d.date||'—'} · $${d.price||0}/day`;if(x.type==='load')return `${d.pickup||'—'} → ${d.delivery||'—'} · ${d.equipment||'—'} · budget $${d.budget||0}`;if(x.type==='warehouse')return `${d.location||'—'} · ${d.pallets||0} pallets · $${d.price||0}/pallet/day`;return `${d.location||'—'} · needs ${d.pallets||0} pallets · max $${d.budget||0}`}
async function loadMarket(){const j=await api('/api/listings');listings=j.listings;const c=t=>listings.filter(x=>x.type===t).length;$('kpis').innerHTML=[['Drivers',c('driver')],['Trucks',c('truck')],['Loads',c('load')],['Warehouses',c('warehouse')]].map(x=>`<div class="kpi"><span class="muted">${x[0]}</span><b>${x[1]}</b></div>`).join('');$('marketList').innerHTML=listings.length?listings.map(x=>`<div class="card"><h3>${labelType(x.type)}</h3><p>${esc(summary(x))}</p><span class="tag">${esc(x.id)}</span>${me&&x.userId===me.id?`<button class="light" style="margin-top:12px" onclick="closeListing('${x.id}')">Close listing</button>`:''}</div>`).join(''):`<div class="card">No open listings yet.</div>`}
async function closeListing(id){await api('/api/listings/'+id,{method:'DELETE'});loadMarket()}
async function seedDemo(){await api('/api/demo',{method:'POST'});await loadMarket();await loadMatches()}
async function loadMatches(){const j=await api('/api/matches');$('matchList').innerHTML=j.matches.length?j.matches.slice(0,30).map(m=>`<div class="card ${m.kind==='load_truck_driver'?'combo':''}"><div class="score">${m.score}/100</div><h3>${m.kind.replaceAll('_',' + ')}</h3>${m.listings.map(x=>`<p><b>${labelType(x.type)}</b><br>${esc(summary(x))}</p>`).join('')}<span class="tag">${m.listings.length>2?'Combined match':'Direct match'}</span></div>`).join(''):`<div class="card">No matches yet.</div>`}
init();

function setPostType(type){const el=$('type');if(el){el.value=type;renderFields()}}
