const $=id=>document.getElementById(id);let me=null,listings=[];
const countries=['United States','Canada','Germany','France','Netherlands','Belgium','Spain','Italy','Poland','Austria','Switzerland','United Kingdom','Ireland','Sweden','Norway','Denmark','Finland','Czechia','Portugal','Greece','Romania','United Arab Emirates','Saudi Arabia','Qatar','Kuwait','Bahrain','Oman','Jordan','Egypt'];
const T={en:{tagline:'Turn Unused Into Transport',market:'Market',post:'Post',matches:'Matches',offers:'Offers',verify:'Verify',heroTitle:'One place for what you have — and what you need.',heroText:'Drivers, trucks, loads and warehouse space. The market chooses the price. TUT Move brings the sides together.',postHaveNeed:'Post I HAVE / I NEED',browse:'Browse market'},ar:{tagline:'حوّل السعة غير المستخدمة إلى حركة',market:'السوق',post:'انشر',matches:'المطابقات',offers:'العروض',verify:'التحقق',heroTitle:'مكان واحد لما لديك — وما تحتاجه.',heroText:'سائقون وشاحنات وحمولات ومساحات تخزين. السوق يحدد السعر وTUT Move يجمع الأطراف.',postHaveNeed:'انشر عندي / أحتاج',browse:'تصفح السوق'},de:{tagline:'Ungenutzte Kapazität in Bewegung bringen',market:'Markt',post:'Inserieren',matches:'Matches',offers:'Angebote',verify:'Verifizieren',heroTitle:'Ein Ort für das, was Sie haben — und brauchen.',heroText:'Fahrer, Lkw, Ladungen und Lagerfläche. Der Markt bestimmt den Preis.',postHaveNeed:'ICH HABE / ICH BRAUCHE',browse:'Markt ansehen'},fr:{tagline:'Transformer la capacité inutilisée en mouvement',market:'Marché',post:'Publier',matches:'Correspondances',offers:'Offres',verify:'Vérifier',heroTitle:'Un seul endroit pour ce que vous avez — et ce dont vous avez besoin.',heroText:'Chauffeurs, camions, chargements et entrepôts. Le marché fixe le prix.',postHaveNeed:"Publier J’AI / J’AI BESOIN",browse:'Voir le marché'},es:{tagline:'Convierte capacidad sin usar en movimiento',market:'Mercado',post:'Publicar',matches:'Coincidencias',offers:'Ofertas',verify:'Verificar',heroTitle:'Un lugar para lo que tienes — y lo que necesitas.',heroText:'Conductores, camiones, cargas y almacenes. El mercado decide el precio.',postHaveNeed:'Publicar TENGO / NECESITO',browse:'Ver mercado'}};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function api(p,o={}){o.headers={'Content-Type':'application/json',...(o.headers||{})};const r=await fetch(p,o);const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Request failed');return j}
function go(id){document.querySelectorAll('.pane').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');if(id==='market')loadMarket();if(id==='matches')loadMatches();if(id==='offers'){loadOffers();loadBookings()}if(id==='adminPane')loadAdmin();if(id==='verify')loadVerification();scrollTo({top:0,behavior:'smooth'})}
function setLanguage(lang){localStorage.setItem('tut_lang',lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(T[lang]&&T[lang][k])el.textContent=T[lang][k]});$('lang').value=lang}
function fillCountries(){for(const id of ['listingCountry','verifyCountry'])$(id).innerHTML=countries.map(c=>`<option>${c}</option>`).join('')}
async function init(){fillCountries();setLanguage(localStorage.getItem('tut_lang')||'en');const j=await api('/api/me');me=j.user;renderAccount();renderAuth();renderFields();togglePrice();await ownerStatus();await loadMarket()}
function renderAccount(){if(me){$('account').innerHTML=`<button class="outlineBtn mini" onclick="go('${me.role==='owner'?'adminPane':'accountPane'}')">${esc(me.name)}</button><button class="linkBtn" onclick="logout()">Logout</button>`;$('adminNav').classList.toggle('hidden',me.role!=='owner')}else{$('account').innerHTML=`<button class="goldBtn mini" onclick="go('accountPane')">Login / Join</button>`;$('adminNav').classList.add('hidden')}}
async function ownerStatus(){const j=await api('/api/owner/status');$('ownerSetup').innerHTML=j.ownerConfigured?'':`<div class="panel ownerSetup"><h3>First-time Owner Setup</h3><p>Create the one platform-owner account. This closes after the first owner is created.</p><input id="oname" placeholder="Owner name"><input id="oemail" type="email" placeholder="Owner email"><input id="opass" type="password" placeholder="Password (10+ characters)"><button class="goldBtn" onclick="setupOwner()">Create Owner Account</button><div id="ownerMsg" class="msg"></div></div>`}
async function setupOwner(){try{const j=await api('/api/owner/setup',{method:'POST',body:JSON.stringify({name:$('oname').value,email:$('oemail').value,password:$('opass').value,language:$('lang').value})});me=j.user;renderAccount();await ownerStatus();go('adminPane')}catch(e){$('ownerMsg').textContent=e.message}}
function renderAuth(){if(me){$('authArea').innerHTML=`<div class="panel"><h3>${esc(me.name)}</h3><p>${esc(me.email)}</p><p>Roles: ${(me.roles||[]).map(esc).join(', ')}</p><p>Verification: <b>${esc(me.verificationStatus)}</b></p></div>`;return}$('authArea').innerHTML=`<div class="authGrid"><div class="panel"><h3>Create account</h3><input id="rname" placeholder="Name"><input id="remail" type="email" placeholder="Email"><input id="rpass" type="password" placeholder="Password (8+ characters)"><label>Your marketplace roles</label><div class="checks">${['driver','truck_owner','carrier','shipper','warehouse_owner'].map(r=>`<label><input type="checkbox" name="role" value="${r}"> ${r.replace('_',' ')}</label>`).join('')}</div><label>Country</label><select id="rcountry">${countries.map(c=>`<option>${c}</option>`).join('')}</select><button class="goldBtn" onclick="register()">Create account</button><div id="rmsg" class="msg"></div></div><div class="panel"><h3>Login</h3><input id="lemail" type="email" placeholder="Email"><input id="lpass" type="password" placeholder="Password"><button class="outlineBtn" onclick="login()">Login</button><div id="lmsg" class="msg"></div></div></div>`}
async function register(){try{const roles=[...document.querySelectorAll('input[name=role]:checked')].map(x=>x.value);const j=await api('/api/register',{method:'POST',body:JSON.stringify({name:$('rname').value,email:$('remail').value,password:$('rpass').value,roles,country:$('rcountry').value,language:$('lang').value,currency:currencyFor($('rcountry').value)})});me=j.user;renderAccount();renderAuth();go('post')}catch(e){$('rmsg').textContent=e.message}}
async function login(){try{const j=await api('/api/login',{method:'POST',body:JSON.stringify({email:$('lemail').value,password:$('lpass').value})});me=j.user;renderAccount();renderAuth();go(me.role==='owner'?'adminPane':'market')}catch(e){$('lmsg').textContent=e.message}}
async function logout(){await api('/api/logout',{method:'POST'});me=null;renderAccount();renderAuth();go('home')}
function currencyFor(c){if(c==='Canada')return'CAD';if(c==='United Kingdom')return'GBP';if(c==='United Arab Emirates')return'AED';if(c==='Saudi Arabia')return'SAR';if(c==='Qatar')return'QAR';if(['United States'].includes(c))return'USD';return'EUR'}
function setIntent(v){$('intent').value=v;$('haveBtn').classList.toggle('active',v==='have');$('needBtn').classList.toggle('active',v==='need');renderFields()}
const schemas={driver:[['location','Location','text','Dallas, TX'],['date','Available date','date',''],['license','Licence / class','text','CDL-A / CE'],['hours','Hours available','number','8'],['endorsements','Endorsements','text','Hazmat, tanker...']],truck:[['location','Truck location','text','Dallas, TX'],['date','Available date','date',''],['equipment','Equipment type','text','Dry van / reefer / flatbed'],['capacity','Capacity','number','20000'],['unit','Capacity unit','text','kg / lb / pallets'],['driverIncluded','Driver included?','text','Yes / No']],load:[['pickup','Pickup','text','Dallas, TX'],['delivery','Destination','text','Houston, TX'],['date','Pickup date','date',''],['equipment','Equipment needed','text','Dry van'],['weight','Weight','number','12000'],['unit','Weight unit','text','kg / lb'],['details','Cargo details','text','20 pallets, non-hazardous']],warehouse:[['location','Warehouse location','text','Dallas, TX'],['from','Available from','date',''],['to','Available to','date',''],['pallets','Pallet positions / area','number','200'],['unit','Unit','text','pallets / m² / ft²'],['capabilities','Capabilities','text','Dock, forklift, chilled...']],storage:[['location','Storage location needed','text','Dallas, TX'],['from','Needed from','date',''],['to','Needed to','date',''],['pallets','Required capacity','number','80'],['unit','Unit','text','pallets / m² / ft²'],['requirements','Requirements','text','Forklift, chilled...']]};
function renderFields(){const r=$('resource').value,i=$('intent').value;let arr=schemas[r]||[];$('fields').innerHTML=`<div class="hint">${i==='have'?'Describe what you can offer.':'Describe exactly what you need.'}</div>`+arr.map(([k,l,t,p])=>`<label>${l}</label><input data-k="${k}" type="${t}" placeholder="${esc(p)}">`).join('')}
function togglePrice(){const m=$('priceMode').value;$('priceWrap').style.display=['request_quotes','open_bidding'].includes(m)?'none':'block'}
async function submitListing(){if(!me){go('accountPane');return}const data={};$('fields').querySelectorAll('[data-k]').forEach(el=>data[el.dataset.k]=el.type==='number'?Number(el.value||0):el.value);try{await api('/api/listings',{method:'POST',body:JSON.stringify({intent:$('intent').value,resource:$('resource').value,title:$('listingTitle').value,country:$('listingCountry').value,currency:$('currency').value,priceMode:$('priceMode').value,price:Number($('price').value||0),data})});$('postMsg').textContent='Published successfully.';loadMarket()}catch(e){$('postMsg').textContent=e.message}}
function listingLabel(x){return `${x.intent==='have'?'I HAVE':'I NEED'} · ${x.resource.toUpperCase()}`}
function priceText(x){if(x.priceMode==='request_quotes')return'Request quotes';if(x.priceMode==='open_bidding')return'Open bidding';if(x.priceMode==='negotiable')return x.price?`${x.currency} ${x.price} · negotiable`:'Negotiable';return`${x.currency} ${x.price}`}
function summary(x){const d=x.data||{};if(x.resource==='driver')return`${d.location||'—'} · ${d.license||'—'} · ${d.date||'—'}`;if(x.resource==='truck')return`${d.location||'—'} · ${d.equipment||'—'} · ${d.date||'—'}`;if(x.resource==='load')return`${d.pickup||'—'} → ${d.delivery||'—'} · ${d.date||'—'}`;return`${d.location||'—'} · ${d.from||'—'} → ${d.to||'—'}`}
async function loadMarket(){const j=await api('/api/listings');listings=j.listings;const fi=$('filterIntent')?.value||'',fr=$('filterResource')?.value||'',fc=($('filterCountry')?.value||'').toLowerCase();const rows=listings.filter(x=>(!fi||x.intent===fi)&&(!fr||x.resource===fr)&&(!fc||(x.country||'').toLowerCase().includes(fc)));$('marketList').innerHTML=rows.length?rows.map(x=>`<article class="card marketCard"><div class="row"><span class="tag">${listingLabel(x)}</span>${x.user?.verified?'<span class="verified">✓ Verified</span>':''}</div><h3>${esc(x.title||listingLabel(x))}</h3><p>${esc(summary(x))}</p><p class="price">${esc(priceText(x))}</p><small>${esc(x.country||'')} · by ${esc(x.user?.name||'Member')}</small><div class="actions">${me&&me.id!==x.userId?`<button class="goldBtn mini" onclick="openOffer('${x.id}','${x.currency}')">Make offer</button>`:''}${me&&me.id===x.userId?`<button class="outlineBtn mini" onclick="closeListing('${x.id}')">Close</button>`:''}</div><div id="offer_${x.id}"></div></article>`).join(''):'<div class="card">No open listings match these filters.</div>'}
function openOffer(id,currency){if(!me){go('accountPane');return}$('offer_'+id).innerHTML=`<div class="offerBox"><input id="oa_${id}" type="number" placeholder="Amount"><input id="om_${id}" placeholder="Message / terms"><button class="goldBtn mini" onclick="sendOffer('${id}','${currency}')">Send offer</button></div>`}
async function sendOffer(id,currency){try{await api('/api/offers',{method:'POST',body:JSON.stringify({listingId:id,amount:Number($('oa_'+id).value),currency,message:$('om_'+id).value})});$('offer_'+id).innerHTML='<div class="msg">Offer sent.</div>'}catch(e){$('offer_'+id).innerHTML=`<div class="msg">${esc(e.message)}</div>`}}
async function closeListing(id){await api('/api/listings/'+id,{method:'DELETE'});loadMarket()}
async function loadMatches(){const j=await api('/api/matches');$('matchList').innerHTML=j.matches.length?j.matches.slice(0,50).map(m=>`<article class="card ${m.kind==='load_truck_driver'?'combo':''}"><div class="score">${m.score}/100</div><h3>${m.kind==='load_truck_driver'?'Load + Truck + Driver':'Potential match'}</h3>${m.listings.map(x=>`<p><b>${listingLabel(x)}</b><br>${esc(summary(x))}</p>`).join('')}</article>`).join(''):'<div class="card">No matches yet.</div>'}
async function loadOffers(){if(!me){$('offerList').innerHTML='<div class="card">Login to view offers.</div>';return}const j=await api('/api/offers');$('offerList').innerHTML=j.offers.length?j.offers.map(o=>`<article class="card"><span class="tag">${esc(o.status)}</span><h3>${o.currency} ${o.amount}</h3><p>${esc(o.message||'No message')}</p>${o.status==='pending'&&o.toUserId===me.id?`<div class="actions"><button class="goldBtn mini" onclick="offerAction('${o.id}','accept')">Accept</button><button class="outlineBtn mini" onclick="counterOffer('${o.id}')">Counter</button><button class="linkBtn" onclick="offerAction('${o.id}','reject')">Reject</button></div>`:''}<div id="counter_${o.id}"></div></article>`).join(''):'<div class="card">No offers yet.</div>'}
async function offerAction(id,action){await api(`/api/offers/${id}/${action}`,{method:'POST',body:'{}'});loadOffers();loadBookings();loadMarket()}
function counterOffer(id){$('counter_'+id).innerHTML=`<div class="offerBox"><input id="ca_${id}" type="number" placeholder="Counter amount"><input id="cm_${id}" placeholder="Terms"><button class="goldBtn mini" onclick="sendCounter('${id}')">Send counter</button></div>`}
async function sendCounter(id){await api(`/api/offers/${id}/counter`,{method:'POST',body:JSON.stringify({amount:Number($('ca_'+id).value),message:$('cm_'+id).value})});loadOffers()}
async function loadBookings(){if(!me){$('bookingList').innerHTML='';return}const j=await api('/api/bookings');$('bookingList').innerHTML=j.bookings.length?j.bookings.map(b=>`<article class="card"><span class="tag">AGREED</span><h3>${b.currency} ${b.agreedPrice}</h3><p>TUT Move fee: ${b.platformFeePct}% = ${b.currency} ${b.platformFee}</p><p>Provider net: ${b.currency} ${b.providerNet}</p><p class="muted">Payment status: ${b.paymentStatus} — payment provider not connected yet.</p></article>`).join(''):'<div class="card">No agreed bookings yet.</div>'}
function fileData(id){return new Promise((resolve,reject)=>{const f=$(id).files[0];if(!f)return resolve(null);if(f.size>3e6)return reject(new Error('Each file must be 3MB or less.'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)})}
async function submitVerification(){if(!me){go('accountPane');return}try{const [license,identity,selfie]=await Promise.all([fileData('licenseFile'),fileData('identityFile'),fileData('selfieFile')]);const j=await api('/api/verification',{method:'POST',body:JSON.stringify({country:$('verifyCountry').value,licenseNumber:$('licenseNumber').value,licenseClass:$('licenseClass').value,expiry:$('licenseExpiry').value,files:{license,identity,selfie}})});me=j.user;renderAccount();$('verifyMsg').innerHTML=`Status: <b>${esc(j.verification.status)}</b><br>${esc(j.verification.message)}`}catch(e){$('verifyMsg').textContent=e.message}}
async function loadVerification(){if(!me){$('verifyMsg').textContent='Login first.';return}const j=await api('/api/verification');if(j.verification)$('verifyMsg').innerHTML=`Current status: <b>${esc(j.verification.status)}</b><br>${esc(j.verification.message||'')}`}
async function loadAdmin(){if(!me||me.role!=='owner')return;const j=await api('/api/admin/summary');$('feePct').value=j.settings.platformFeePct;$('defaultCurrency').value=j.settings.defaultCurrency;for(const k of ['brandName','siteUrl','ownerName','ownerEmail','legalEntity','supportEmail']){if($(k))$(k).value=j.settings[k]||'';}const s=j.stats;$('adminArea').innerHTML=`<div class="kpis"><div class="kpi"><span>Users</span><b>${s.users}</b></div><div class="kpi"><span>Open listings</span><b>${s.openListings}</b></div><div class="kpi"><span>Offers</span><b>${s.offers}</b></div><div class="kpi"><span>Bookings</span><b>${s.bookings}</b></div><div class="kpi"><span>Platform revenue*</span><b>${s.platformRevenue}</b></div></div><p class="muted">*Calculated from agreed bookings only; no real payment has been captured in this MVP.</p><h2 class="subhead">Users</h2><div class="cards">${j.users.map(u=>`<div class="card"><h3>${esc(u.name)}</h3><p>${esc(u.email)}</p><p>${esc((u.roles||[]).join(', '))} · ${esc(u.country||'')}</p><span class="tag">${esc(u.verificationStatus)}</span></div>`).join('')}</div><h2 class="subhead">Recent bookings</h2><div class="cards">${j.bookings.slice(-20).reverse().map(b=>`<div class="card"><h3>${b.currency} ${b.agreedPrice}</h3><p>Fee ${b.platformFeePct}% = ${b.currency} ${b.platformFee}</p><span class="tag">${b.status}</span></div>`).join('')||'<div class="card">No bookings yet.</div>'}</div>`}
async function saveOwnership(){const body={brandName:$('brandName').value,siteUrl:$('siteUrl').value,ownerName:$('ownerName').value,ownerEmail:$('ownerEmail').value,legalEntity:$('legalEntity').value,supportEmail:$('supportEmail').value};const j=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify(body)});alert('Ownership settings saved for '+(j.settings.siteUrl||'TUT Move'));}
async function saveSettings(){const j=await api('/api/admin/settings',{method:'PUT',body:JSON.stringify({platformFeePct:Number($('feePct').value),defaultCurrency:$('defaultCurrency').value})});alert(`Saved: ${j.settings.platformFeePct}%`) }
init();
